import { pool } from '../config/db.js';
import { buildCode } from '../utils/codes.js';
import { audit } from '../services/audit.js';

async function fy(companyId){const [[r]]=await pool.query('SELECT code FROM fiscal_years WHERE company_id=? AND is_current=1 LIMIT 1',[companyId]);return (r?.code||'2083-84').split('-')[0];}
async function nextCode(table,prefix,companyId,width=5){const [[r]]=await pool.query(`SELECT COUNT(*)+1 n FROM ${table} WHERE company_id=?`,[companyId]);return buildCode(prefix,await fy(companyId),r.n,width);}

export async function listInvoices(req,res,next){try{const [rows]=await pool.query(`SELECT i.*,c.name client_name,p.project_name FROM invoices i LEFT JOIN clients c ON c.id=i.client_id LEFT JOIN projects p ON p.id=i.project_id WHERE i.company_id=? AND i.is_deleted=0 ORDER BY i.id DESC`,[req.user.company_id]);res.json(rows)}catch(e){next(e)}}
export async function createInvoice(req,res,next){try{
  const b=req.body,c=req.user.company_id; const no=await nextCode('invoices','INV',c); const items=Array.isArray(b.items)?b.items:[];
  const subtotal=items.reduce((s,x)=>s+Number(x.quantity||0)*Number(x.rate||0),0); const discount=Number(b.discount||0); const taxable=Math.max(0,subtotal-discount); const vatRate=Number(b.vat_rate||0); const vat=taxable*vatRate/100; const grand=taxable+vat;
  const conn=await pool.getConnection(); try{await conn.beginTransaction(); const [r]=await conn.query(`INSERT INTO invoices(company_id,invoice_no,invoice_date,client_id,project_id,pan_vat_no,subtotal,discount,taxable_amount,vat_rate,vat_amount,grand_total,paid_amount,due_amount,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,0,?,'Issued',?)`,[c,no,b.invoice_date||new Date(),b.client_id||null,b.project_id||null,b.pan_vat_no||null,subtotal,discount,taxable,vatRate,vat,grand,grand,req.user.id]); for(const x of items){const amount=Number(x.quantity||0)*Number(x.rate||0);await conn.query(`INSERT INTO invoice_items(company_id,invoice_id,description,unit,quantity,rate,amount) VALUES(?,?,?,?,?,?,?)`,[c,r.insertId,x.description,x.unit||null,x.quantity||0,x.rate||0,amount]);} await conn.commit(); await audit(req,'CREATE','invoices',r.insertId,{invoice_no:no,grand_total:grand}); res.status(201).json({id:r.insertId,invoice_no:no,subtotal,discount,taxable_amount:taxable,vat_amount:vat,grand_total:grand});}catch(e){await conn.rollback();throw e}finally{conn.release()}
}catch(e){next(e)}}

export async function listPayments(req,res,next){try{const [rows]=await pool.query(`SELECT py.*,c.name client_name,p.project_name FROM payments py LEFT JOIN clients c ON c.id=py.client_id LEFT JOIN projects p ON p.id=py.project_id WHERE py.company_id=? AND py.is_deleted=0 ORDER BY py.id DESC`,[req.user.company_id]);res.json(rows)}catch(e){next(e)}}
export async function createPayment(req,res,next){try{const b=req.body,c=req.user.company_id;const receipt=await nextCode('payments','RCPT',c);const [r]=await pool.query(`INSERT INTO payments(company_id,receipt_no,payment_date,client_id,project_id,invoice_id,amount,payment_method,reference_no,status,remarks,created_by) VALUES(?,?,?,?,?,?,?,?,?,'Successful',?,?)`,[c,receipt,b.payment_date||new Date(),b.client_id||null,b.project_id||null,b.invoice_id||null,b.amount,b.payment_method||'Cash',b.reference_no||null,b.remarks||null,req.user.id]);if(b.invoice_id){await pool.query(`UPDATE invoices SET status=CASE WHEN paid_amount+?>=grand_total THEN 'Paid' ELSE 'Partially Paid' END,paid_amount=LEAST(grand_total,paid_amount+?),due_amount=GREATEST(0,grand_total-(paid_amount+?)) WHERE id=? AND company_id=?`,[b.amount,b.amount,b.amount,b.invoice_id,c]);}await audit(req,'CREATE','payments',r.insertId,{receipt_no:receipt,amount:b.amount});res.status(201).json({id:r.insertId,receipt_no:receipt})}catch(e){next(e)}}
