import { useEffect,useState } from 'react';import api from '../services/api';import Modal from '../components/Modal';import DataTable from '../components/DataTable';
const configs={
 clients:{title:'Clients',fields:[['name','Client Name','text'],['contact_person','Contact Person','text'],['phone','Phone','text'],['email','Email','email'],['address','Address','text'],['pan_vat_no','PAN / VAT','text']],cols:[['name','Client'],['phone','Phone'],['email','Email'],['address','Address'],['pan_vat_no','PAN/VAT']]},
 suppliers:{title:'Suppliers',fields:[['name','Supplier Name','text'],['contact_person','Contact Person','text'],['phone','Phone','text'],['email','Email','email'],['address','Address','text'],['pan_vat_no','PAN / VAT','text'],['opening_due','Opening Due','number']],cols:[['name','Supplier'],['phone','Phone'],['address','Address'],['opening_due','Opening Due']]},
 materials:{title:'Materials',fields:[['name','Material Name','text'],['sku','SKU','text'],['unit','Unit','text'],['opening_stock','Opening Stock','number'],['minimum_stock','Minimum Stock','number'],['default_unit_cost','Unit Cost','number']],cols:[['name','Material'],['sku','SKU'],['unit','Unit'],['opening_stock','Opening'],['minimum_stock','Minimum']]},
 employees:{title:'Employees & Labour',fields:[['employee_code','Employee Code','text'],['name','Name','text'],['employee_type','Type','select',['Employee','Labour']],['designation','Designation','text'],['phone','Phone','text'],['salary_type','Salary Type','select',['Monthly','Daily']],['basic_salary','Basic Salary','number'],['daily_wage','Daily Wage','number']],cols:[['employee_code','Code'],['name','Name'],['employee_type','Type'],['designation','Designation'],['salary_type','Salary'],['daily_wage','Daily Wage']]},
 expenses:{title:'Expenses',fields:[['expense_date','Expense Date','date'],['expense_type','Type','select',['Material','Labour','Transport','Fuel','Equipment','Food','Office','Miscellaneous','Other']],['description','Description','text'],['amount','Amount','number'],['payment_method','Payment Method','text'],['reference_no','Reference No.','text']],cols:[['expense_date','Date'],['expense_type','Type'],['description','Description'],['amount','Amount'],['payment_method','Method']]},
 equipment:{title:'Equipment',fields:[['equipment_code','Code','text'],['name','Equipment Name','text'],['type','Type','text'],['purchase_cost','Purchase Cost','number'],['current_value','Current Value','number'],['status','Status','select',['Available','Assigned','On Site','Rented Out','Maintenance','Damaged','Inactive']]],cols:[['equipment_code','Code'],['name','Equipment'],['type','Type'],['status','Status'],['current_value','Current Value']]}
};
export default function CrudPage({resource}){const cfg=configs[resource], [rows,setRows]=useState([]),[open,setOpen]=useState(false),[form,setForm]=useState({}),[err,setErr]=useState('');const load=()=>api.get('/'+resource).then(r=>setRows(r.data));useEffect(()=>{load()},[resource]);async function save(e){e.preventDefault();setErr('');try{await api.post('/'+resource,form);setOpen(false);setForm({});load()}catch(e){setErr(e.response?.data?.message||'Save failed')}}const columns=cfg.cols.map(([key,label])=>({key,label,render:key==='amount'||key.includes('cost')||key==='daily_wage'||key==='opening_due'||key==='current_value'?r=>'Rs. '+Number(r[key]||0).toLocaleString('en-IN'):undefined}));return <><div className="page-head"><div><h1>{cfg.title}</h1><p>Manage {cfg.title.toLowerCase()} and related records.</p></div><button className="btn primary" onClick={()=>setOpen(true)}>+ Add {cfg.title.replace('Employees & Labour','Employee').replace(/s$/,'')}</button></div><div className="panel"><DataTable rows={rows} columns={columns}/></div><Modal open={open} title={`Add ${cfg.title}`} onClose={()=>setOpen(false)}><form className="form-grid" onSubmit={save}>{err&&<div className="alert danger full">{err}</div>}{cfg.fields.map(([key,label,type,opts])=><label key={key}>{label}{type==='select'?<select value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}><option value="">Select</option>{opts.map(o=><option key={o}>{o}</option>)}</select>:<input type={type} step={type==='number'?'0.01':undefined} value={form[key]||''} onChange={e=>setForm({...form,[key]:e.target.value})}/>}</label>)}<div className="form-actions full"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn primary">Save</button></div></form></Modal></>}
